### ISSUE TITLE
Add a security policy

### ISSUE THREAD

**Issue by zidingz** [Mostafa-Samir/zip-local#14]
Hey there!

I belong to an open source security research community, and a member (@7he6uzzer) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by Mostafa-Samir** [comment]
Done!
Thank you.

**Comment by JamieSlome** [comment]
@Mostafa-Samir - thanks for this! ⚡ 

We sent you a couple of e-mails, just wanted to check in and see if you got these? Alternatively, you can view the report directly here:

https://huntr.dev/bounties/bda59d27-59cb-41ae-85a1-7387dc851b0f/

**Comment by Mostafa-Samir** [comment]
Hello @JamieSlome 

Yeah, the emails were received, but Gmail placed them in the wrong category so I didn't see them till I went and looked for them after your comment 😅 I'll follow up on the report 👍

**Comment by JamieSlome** [comment]
Thanks, @Mostafa-Samir! ⚡
