### ISSUE TITLE
Unzip, remove files from library and create a new zip

### ISSUE THREAD

**Issue by stefanwalther** [Mostafa-Samir/zip-local#2]
Hi,

great library, working much better than everything else I have tried before.
I am struggling to figure out how this workflow can be achieved:

I want to
- unzip a file (in memory)
- remove some files
- create a new zip file on the fly (without having to unzip everything to a folder, just working in memory).

Any hint would be highly appreciated, thx!

Regards
Stefan

**Comment by Mostafa-Samir** [comment]
Hello,

Thanks for your feedback.
- When you say **unzip a file (in memory)**, do you mean that you want to unzip a file that is already in memory (e.g. a file that came through a network connection) without reading it from disk or do you mean that you want to unzip a file from disk but have its content in memory ?
- removing files is not currently available in the library. I'll start working on it.
- I don't understand very clearly what do you want in that last point, so please elaborate more.

Thanks.

**Comment by Mostafa-Samir** [comment]
Please review the changelog, check the two newly added features and see if they achieve any of your work flow.
They solve the second one and probably the first one. I'm not sure about the third one as I don't understand it.

**Comment by Mostafa-Samir** [comment]
After taking another look at your workflow I think I understand it know. I updated the library with some new features that achieves that workflow , review the changelog and check them.
You can also refer to the code example [here](https://github.com/Mostafa-Samir/zip-local#low-level-operations), I think it's very close to your workflow.

**Comment by stefanwalther** [comment]
Great, thx, I'll give it immediately a try.

**Comment by stefanwalther** [comment]
Hi, seems to work fine, but 

``` js
var files = unzippedFs.contents();
```

only contains files and not folders, is this by intention?

Regards
Stefan
