### ISSUE TITLE
zip.save(…) does not invoke callback when path to zip file does not exist.

### ISSUE THREAD

**Issue by simon-scherzinger** [Mostafa-Samir/zip-local#4]
First of all: Thanks for this awesome and simple zipping tool. :) Sadly I was getting some weird behaviour with saving a zip file. When using `zip.save('path/to/file.zip', (err) => errorHandler);` the callback won't come back when `path/to` does not exist. At least an error should be passed to the callback.

A workaround for now is using `fsExtra.ensureDir(path.dirname('path/to/file.zip'));`. But I will obviously require `fs-extra`.

**Comment by Mostafa-Samir** [comment]
Thanks a lot for your feedback!

The problem should be fixed now, please check and let me know.
