### ISSUE TITLE
Error when zip has a folder that exists

### ISSUE THREAD

**Issue by JoniJnm** [Mostafa-Samir/zip-local#5]
Using v0.3.3.

If the zip has a folder, and it exists, zip-local try to make it throwing an error

`Error: EEXIST: file already exists, mkdir 'D:\clientes\ivan\tienda\web\test\myfolder' at Error (native)`

I used this test:
- /
- /gulpfile.js
- /test
- /test/test.zip

Zip content:
- /
- /myfolder
- /myfolder/file.txt

``` js
gulp.task('test', function(cb) {
    var zipper = require('zip-local');
    var FS = require('fs');

    var folder = './test';
    var zipFile = folder + '/test.zip';

    zipper.unzip(zipFile, function(err, unzipped) {
        if (err) {
            return cb(err);
        }
        var outputFolder = FS.realpathSync(folder);
        unzipped.save(outputFolder, function(err) {
            if (err) {
                return cb(err);
            }

            cb(); //OK!
        });
    });
});
```

Execute `gulp test` twice to see the error (when myfolder exists)

The solution is, I think, to check if the folder exists before create it.

**Comment by Mostafa-Samir** [comment]
Thank you for your feedback. The issue should be fixed now.
Feel free to reopen the issue if you have any further problems.
